kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.userName }}-argocd-argocd-application-controller
  namespace: {{ .Values.userName }}-application
subjects:
  - kind: ServiceAccount
    name: {{ .Values.userName }}-argocd-argocd-application-controller
    namespace: {{ .Values.userName }}-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admins