apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: {{ .Values.userName }}-

resources:
- ../../base
- namespace.yaml
- RB-1.yaml
- RB-2.yaml
- CRB.yaml
- group.yaml


patchesStrategicMerge:
- argocd.yaml

